name: Publish
on:
  push:
    tags:
    - 'v0.4.*'
  workflow_dispatch:

jobs:
  check-compiles:
    name: Test compilation of all modules
    runs-on: ubuntu-22.04
    if: github.repository == 'scala-native/scala-native'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linux-setup-env
        with:
          scala-version: "2.13" #Unused, any version can be placed here
          java-version: 8

      - name: Compile everything
        run: sbt "-v" "-J-Xmx7G" "++3.1.3; Test/compile; ++2.13.12; Test/compile; ++2.12.18; Test/compile"

  publish:
    name: Publish
    runs-on: ubuntu-22.04
    needs: [check-compiles]
    if: github.repository == 'scala-native/scala-native'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linux-setup-env
        with:
          scala-version: "2.13.12" #Unused, any version can be placed here
          java-version: 8

      - name: Setup PGP Key
        run: |
          echo -n "$PGP_SECRET" | base64 --decode | gpg --batch --import
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}

      - name: Publish release
        env:
          MAVEN_USER: "${{ secrets.SONATYPE_USER }}"
          MAVEN_PASSWORD: "${{ secrets.SONATYPE_PASSWORD }}"
          PGP_PASSPHRASE: "${{ secrets.PGP_PASSWORD }}"
        run: sbt "-v" "-no-colors" "-J-Xmx5G" "clean; ++3.1.3; publishRelease"
